<!DOCTYPE html>
<html>
<head>

<link rel="icon" href="favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
<title>BatiCasa</title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://unpkg.com/chota@latest">
</head>

<body class="dark">

<div id="siteheader">
<h1>Nico Brailovsky's blog</h1>

<div class="nav tabs is-full">
  <a href="/">Home</a>
  <a href="/blog/index.html">Blog</a>
  <a href="/blog/index.html">Series</a>
  <a href="/blog/history.html">Archive</a>
  <a href="/blog/index.html">About</a>
</div>

</div>

<h1>C++ exceptions under the hood 7: a nice personality<a name="cexceptionsunderthehood7anicepersonality"></a></h1>
<p>On our journey to learn about exceptions we have learned so far how a throw is done, that something called "call frame information" helps a library called Unwind to do the stack unwinding, and that the compiler writes something called LSDA, language specific data area, to know which exceptions can a method handle. And we know by now that a lot of magic is done on the personality function; we've never seen it in action though. Let's recap in a bit more of detail about how an exception will be thrown and caught (or, more precisely, how we know so far it will be thrown caught):</p>
<ul>
<li>The compiler will translate our throw statement into a pair of <strong>__cxa_allocate_exception/__cxa_throw</strong></li>
<li><strong>__cxa_allocate_exception</strong> will create the exception in memory</li>
<li><strong>__cxa_throw</strong> will initialize a bunch of stuff and forward this exception to a lower-level unwind library by calling <strong>_Unwind_RaiseException</strong></li>
<li>Unwind will use CFI to know which functions are on the stack (ie to know how to start the stack unwinding)</li>
<li>Each function will have an LSDA (language specific data area) part, added into something called <strong>".gcc_except_table"</strong></li>
<li>Unwind will invoke the personality function with the current stack frame and the LSDA; this function should reply to unwind whether this stack can handle the exception or not</li>
</ul>
<p>Knowing this, it's about time we implement our own personality function. Our ABI used to print this when an exception was thrown:</p>
<pre lang="c++"><code lang="c++">alloc ex 1
__cxa_throw called
no one handled __cxa_throw, terminate!
</code></pre>
<p>Let's go back to our mycppabi and let's add something like this (link to full mycppabi.cpp file):</p>
<pre lang="c++"><code lang="c++">void __gxx_personality_v0()
{
    printf("Personality function FTW\n");
}
</code></pre>
<p>Note: You can download the full sourcecode for this project <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v02">in my github repo</a>.</p>
<p>And sure enough, when we run it we should see our personality function being called. We know we're on the right track and now we have an idea of what we want for our personality function; let's start using the proper definition for this function:</p>
<pre lang="c++"><code lang="c++">_Unwind_Reason_Code __gxx_personality_v0 (
                     int version, _Unwind_Action actions, uint64_t exceptionClass,
                     _Unwind_Exception<em> unwind_exception, _Unwind_Context</em> context);
</code></pre>
<p>If we put that into our mycppabi.cpp file we get:</p>
<pre lang="c++"><code lang="c++">#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
namespace __cxxabiv1 {
    struct __class_type_info {
        virtual void foo() {}
    } ti;
}
#define EXCEPTION_BUFF_SIZE 255
char exception_buff[EXCEPTION_BUFF_SIZE];
extern "C" {
void<em> __cxa_allocate_exception(size_t thrown_size)
{
    printf("alloc ex %i\n", thrown_size);
    if (thrown_size &gt; EXCEPTION_BUFF_SIZE) printf("Exception too big");
    return &amp;exception_buff;
}
void __cxa_free_exception(void </em>thrown_exception);
#include <unwind.h>
typedef void (<em>unexpected_handler)(void);
typedef void (</em>terminate_handler)(void);
struct __cxa_exception {
    std::type_info *    exceptionType;
    void (<em>exceptionDestructor) (void </em>);
    unexpected_handler  unexpectedHandler;
    terminate_handler   terminateHandler;
    __cxa_exception *   nextException;
    int         handlerCount;
    int         handlerSwitchValue;
    const char *        actionRecord;
    const char *        languageSpecificData;
    void *          catchTemp;
    void *          adjustedPtr;
    _Unwind_Exception   unwindHeader;
};
void __cxa_throw(void<em> thrown_exception, struct type_info </em>tinfo, void (<em>dest)(void</em>))
{
    printf("__cxa_throw called\n");
    __cxa_exception <em>header = ((__cxa_exception </em>) thrown_exception - 1);
    _Unwind_RaiseException(&amp;header-&gt;unwindHeader);
    // __cxa_throw never returns
    printf("no one handled __cxa_throw, terminate!\n");
    exit(0);
}
void __cxa_begin_catch()
{
    printf("begin FTW\n");
}
void __cxa_end_catch()
{
    printf("end FTW\n");
}
_Unwind_Reason_Code __gxx_personality_v0 (
                     int version, _Unwind_Action actions, uint64_t exceptionClass,
                     _Unwind_Exception<em> unwind_exception, _Unwind_Context</em> context)
{
    printf("Personality function FTW!\n");
}
}
</code></pre>
<p>Code @ <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v02">my github repo</a>.</p>
<p>Let's compile and link everything, then run it and start by analyzing each param to this function with some help of gdb:</p>
<pre lang="c++"><code lang="c++">Breakpoint 1, __gxx_personality_v0 (version=1, actions=1, exceptionClass=134514792, unwind_exception=0x804a060, context=0xbffff0f0)
</code></pre>
<ul>
<li>The version and the exceptionClass are related to language/ABI/compiler toolchain/native or non-native exception, etc. We don't need to worry about it for our mini ABI, we'll just handle all the exceptions.</li>
<li>Actions: this is what _Unwind_ uses to tell the personality function what it should do (more on that later)</li>
<li>unwind_exception: the exception allocated by __cxa_allocate_exception (kind of... there's a lot of pointer arithmetic going on but that pointer can be used to access our original exception anyway)</li>
<li>context: this holds all the information regarding the current stack frame, for example the language specific data area (LSDA). This is what we will be using to detect whether this stack can handle the thrown exception (and also to detect whether we need to run any destructors)</li>
</ul>
<p>So there we have it, a working (well, linkeable) personality function. Doesn't do much, though, so next time we'll start adding some real behavior and try to make it handle an exception.</p>
<h1>Comments<a name="comments"></a></h1>
<hr />
<h2>In reply to <a href="">this post</a>, <a href="">Anonymous</a> commented @ 2018-01-04T10:47:04.000+01:00:<a name="inreplytothispostanonymouscommented20180104t104704.0000100"></a></h2>
<p>But .gcc_except_table is same with .eh_frame. (ubuntu Ubuntu 14.04.5 LTS, gcc gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4)</p>
<p>Original <a href="/blog/2013/0319_Cexceptionsunderthehood7anicepersonality.html">published here</a>.</p>
<hr />
<p><a href="/blog/2013/0319_Cexceptionsunderthehood7anicepersonality.html">Permalink</a> -
<a href="https://github.com/nicolasbrailo/nicolasbrailo.github.io/issues/new?title=Comment@/blog_md/2013/0319_Cexceptionsunderthehood7anicepersonality.md&amp;body=I%20have%20a%20comment!">Leave a comment</a></p>

<div id="sitefooter">
Page generated 2024-02-05
</div>

</body>
</html>
