<h1>C++ exceptions under the hood 15: finding the right landing pad<a name="cexceptionsunderthehood15findingtherightlandingpad"></a></h1>
<p>This is now the 15th installment in what&rsquo;s becoming the longest series I&rsquo;ve written for this blog; we have so far learned how exceptions are thrown and we have written a personality function capable of, with some sort of reflexion, detecting where the catch-blocks are (landing pads, in exception speak). In the last article we wrote a personality function that can handle exceptions, but it does so only with the first landing pad of the first call frame in the stack. Let&rsquo;s improve that a little bit, let&rsquo;s make our personality function capable of choosing the right landing pad in a function with multiple landing pads.</p>
<p>In a TDD fashion we can first build a test for our ABI. Let&rsquo;s modify our test program, throw.cpp, to have two try/catch blocks:</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">#include &amp;lt;stdio.h&amp;gt;
#include &quot;throw.h&quot;
struct Fake_Exception {};
void raise() {
    throw Exception();
}
void try_but_dont_catch() {
    try {
        printf(&quot;Running a try which will never throw.\n&quot;);
    } catch(Fake_Exception&amp;amp;) {
        printf(&quot;Exception caught&hellip; with the wrong catch!\n&quot;);
    }
    try {
        raise();
    } catch(Fake_Exception&amp;amp;) {
        printf(&quot;Caught a Fake_Exception!\n&quot;);
    }
    printf(&quot;try_but_dont_catch handled the exception\n&quot;);
}
void catchit() {
    try {
        try_but_dont_catch();
    } catch(Fake_Exception&amp;amp;) {
        printf(&quot;Caught a Fake_Exception!\n&quot;);
    } catch(Exception&amp;amp;) {
        printf(&quot;Caught an Exception!\n&quot;);
    }
    printf(&quot;catchit handled the exception\n&quot;);
}
extern &quot;C&quot; {
    void seppuku() {
        catchit();
    }
}
</pre>
<p>Before you test it, try to think about what will happen upon running this test. Focus on the try_but_dont_catch function: the first try/catch block will not throw, then the second block will throw. Since our ABI is quite dumb the first block will handle the second block&rsquo;s exception. What will happen after the first block has finished handling the exception? The execution will resume from where the catch/try ends, thus entering again on the second try/catch block. Infinite loop! We have reinvented yet again a very complicated while(true).</p>
<p>Let&rsquo;s use our knowledge of the start/length fields in the call site table (LSDA) to properly choose our landing pad. For this we will need to know what the instruction pointer was when the exception was thrown, and we can do this with an _Unwind_ function we already know: _Unwind_GetIP. To understand what _Unwind_GetIP will return let&rsquo;s see an example:</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">void f1() {}
void f2() { throw 1; }
void f3() {}
void foo() {
L1:
    try{ f1(); } catch(&hellip;) {}
L2:
    try{ f2(); } catch(&hellip;) {}
L3:
    try{ f3(); } catch(&hellip;) {}
}
</pre>
<p>In this case our personality function would be called for the catch block for f2 and the stack would be like this:</p>
<pre style="display: inline-block; border: 1px solid red;">+------------------------------+
|   IP: f2  stack frame: f2    |
+------------------------------+
|   IP: L3  stack frame: foo   |
+------------------------------+
</pre>
<p>Note that IP will be at L3 but the exception will be thrown in L2; this is because the IP will point to the next instruction to execute. This also means we need to substract one if we need to find the IP where an exception was thrown, otherwise the result from _Unwind_GetIP would not be in the range of our landing pad. Back to our personality function:</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">_Unwind_Reason_Code __gxx_personality_v0 (
                             int version,
                             _Unwind_Action actions,
                             uint64_t exceptionClass,
                             _Unwind_Exception<em> unwind_exception,
                             _Unwind_Context</em> context)
{
    if (actions &amp;amp; _UA_SEARCH_PHASE)
    {
        printf(&quot;Personality function, lookup phase\n&quot;);
        return _URC_HANDLER_FOUND;
    } else if (actions &amp;amp; _UA_CLEANUP_PHASE) {
        printf(&quot;Personality function, cleanup\n&quot;);
        // Calculate what the instruction pointer was just before the
        // exception was thrown for this stack frame
        uintptr_t throw_ip = _Unwind_GetIP(context) - 1;
        // Pointer to the beginning of the raw LSDA
        LSDA_ptr lsda = (uint8_t*)_Unwind_GetLanguageSpecificData(context);
        // Read LSDA headerfor the LSDA
        LSDA_Header header(&amp;amp;lsda);
        // Read the LSDA CS header
        LSDA_CS_Header cs_header(&amp;amp;lsda);
        // Calculate where the end of the LSDA CS table is
        const LSDA_ptr lsda_cs_table_end = lsda + cs_header.length;
        // Loop through each entry in the CS table
        while (lsda &amp;lt; lsda_cs_table_end)
        {
            LSDA_CS cs(&amp;amp;lsda);
            // If there&amp;#x27;s no LP we can&amp;#x27;t handle this exception; move on
            if (not cs.lp) continue;
            uintptr_t func_start = _Unwind_GetRegionStart(context);
            // Calculate the range of the instruction pointer valid for this
            // landing pad; if this LP can handle the current exception then
            // the IP for this stack frame must be in this range
            uintptr_t try_start = func_start + cs.start;
            uintptr_t try_end = func_start + cs.start + cs.len;
            // Check if this is the correct LP for the current try block
            if (throw_ip &amp;lt; try_start) continue;
            if (throw_ip &amp;gt; try_end) continue;
            // We found a landing pad for this exception; resume execution
            int r0 = __builtin_eh_return_data_regno(0);
            int r1 = __builtin_eh_return_data_regno(1);
            _Unwind_SetGR(context, r0, (uintptr_t)(unwind_exception));
            // Note the following code hardcodes the exception type;
            // we&amp;#x27;ll fix that later on
            _Unwind_SetGR(context, r1, (uintptr_t)(1));
            _Unwind_SetIP(context, func_start + cs.lp);
            break;
        }
        return _URC_INSTALL_CONTEXT;
    } else {
        printf(&quot;Personality function, error\n&quot;);
        return _URC_FATAL_PHASE1_ERROR;
    }
}
</pre>
<p>As usual: You can download the full sourcecode for this project <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v07">in my github repo</a>.</p>
<p>Try the example again and voila, no more infinite loop! That was a simple change and we can now choose the correct landing pad. Next time we&rsquo;ll try to make our personality function also pick the correct stack frame instead of choosing the first one.</p>